livre_public:
    pattern:  /{page}
    defaults: { _controller: "WalvaHafBundle:PublicLivre:index", "page":1 }

#
#livre_public_list:
#    pattern:  /page/{page}
#    defaults: { _controller: "WalvaHafBundle:PublicLivre:index" }

livre_public_show:
    pattern:  /{id}/show
    defaults: { _controller: "WalvaHafBundle:PublicLivre:show" }

livre_public_menu:
    pattern:  /menu
    defaults: { _controller: "WalvaHafBundle:PublicLivre:menu" }
